In [ ]:
# import pandas as pd
# campaign = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank.csv')

# import polars as pl
# campaign = pl.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank.csv', schema_overrides={'nr.employed': pl.Float64})

In [17]:
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
bank = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank.csv')

bank.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [18]:
X = bank.drop('y', axis=1)
y = bank['y']

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [19]:
model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight='balanced',
    max_depth = 7
)

In [20]:
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

          no       0.95      0.86      0.90      6572
         yes       0.37      0.63      0.47       842

    accuracy                           0.84      7414
   macro avg       0.66      0.75      0.69      7414
weighted avg       0.88      0.84      0.85      7414

[[5676  896]
 [ 308  534]]

In [22]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred, labels=['no', 'yes'])

tn = cm[0][0]  # actual no, predicted no
fp = cm[0][1]  # actual no, predicted yes
fn = cm[1][0]  # actual yes, predicted no
tp = cm[1][1]  # actual yes, predicted yes

print("Actual no predicted no:", tn)
print("Actual no predicted yes:", fp)
print("Actual yes predicted no:", fn)
print("Actual yes predicted yes:", tp)

accuracy = (tn + tp) / (tn + fp + fn + tp)
yes_precision = tp / (tp + fp)
yes_recall = tp / (tp + fn)
no_recall = tn / (tn + fp)

print("Accuracy:", accuracy)
print("Yes precision:", yes_precision)
print("Yes recall:", yes_recall)
print("No recall:", no_recall)

Actual no predicted no: 5676
Actual no predicted yes: 896
Actual yes predicted no: 308
Actual yes predicted yes: 534
Accuracy: 0.8376045319665498
Yes precision: 0.3734265734265734
Yes recall: 0.6342042755344418
No recall: 0.8636640292148509

In [27]:
holdout_mini = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank_holdout_test_mini.csv')

holdout_mini.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
0,26,blue-collar,married,basic.9y,unknown,yes,no,cellular,jul,tue,2,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1
1,33,admin.,married,high.school,no,yes,no,cellular,may,tue,1,999,0,nonexistent,-1.8,92.893,-46.2,1.344,5099.1
2,45,admin.,divorced,university.degree,no,no,yes,cellular,jun,wed,1,3,2,success,-1.7,94.055,-39.8,0.739,4991.6
3,37,admin.,divorced,high.school,no,yes,no,telephone,jun,fri,12,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1
4,34,admin.,single,high.school,no,no,no,cellular,nov,wed,1,999,0,nonexistent,-0.1,93.200,-42.0,4.120,5195.8

In [35]:
holdout_mini_encoded = pd.get_dummies(holdout_mini, drop_first = True)
holdout_mini_encoded = holdout_mini_encoded.reindex(columns = X.columns, fill_value = 0)
mini_predictions = model.predict(holdout_mini_encoded)
mini_predictions

array(['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes',
       'yes', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no',
       'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes',
       'no', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'yes', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'yes', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes',
       'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no'], dtype=object)

In [39]:
mini_submission = pd.DataFrame({
    'predictions': mini_predictions
})

mini_submission.head()

  predictions
0          no
1          no
2         yes
3          no
4          no

In [44]:
mini_submission.to_csv('team3-module2-mini-predictions.csv',index = False)

print(mini_submission.shape)
print(mini_submission['predictions'].value_counts())

(410, 1)
predictions
no     337
yes     73
Name: count, dtype: int64